---
name: "jellyfin-plugin-aleator"
guid: "e9a8b6c0-3a6b-4e1e-a7e6-63d03a45893b"
version: "1.0.0" # Increment with each new version
jellyfin_version: "10.9.11" # Adjust based on compatibility
owner: "yababakets"
nicename: "Aleator"
description: "Aleator plugin displays shuffled content from selected libraries on the home screen."
overview: "Aleator plugin lets users configure and display random selections of movies or shows from selected libraries on the home screen."
category: "General"
artifacts:
  - "Jellyfin.Plugin.Aleator.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "net8.0" # Adjust based on Jellyfin plugin compatibility
