---
name: "jellyfin-plugin-aleator"
guid: "E9A8B6C0-3A6B-4E1E-A7E6-63D03A45893B"
version: "1.0.0" # Increment with each new version
jellyfin_version: "10.9.11" # Adjust based on compatibility
owner: "yababakets"
nicename: "Aleator"
description: "Aleator plugin displays shuffled content from selected libraries on the home screen."
overview: "Aleator plugin lets users configure and display random selections of movies or shows from selected libraries on the home screen."
category: "General"
artifacts:
  - "Jellyfin.Plugin.Aleator.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "net6.0" # Set to net6.0 for compatibility with .NET 6
